export enum Steps {
    SETUP = 'SETUP',
    DOWNLOADING_LUNA = 'DOWNLOADING_LUNA',
    EXTRACTING_LUNA = 'EXTRACTING_LUNA',
    COPYING_ASAR_INSTALL = 'COPYING_ASAR_INSTALL',
    INSERTING_LUNA = 'INSERTING_LUNA',
    UNINSTALLING_LUNA = 'UNINSTALLING_LUNA',
    UNINSTALLING_NEPTUNE = 'UNINSTALLING_NEPTUNE',
    COPYING_ASAR_UNINSTALL = 'COPYING_ASAR_UNINSTALL',
    KILLING_TIDAL = 'KILLING_TIDAL'
}